name: Deploy to DO Droplet

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DO Droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ vars.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            export GIT_SSH_COMMAND=/home/frappe-bench/custom-ssh.sh
            cd /home/frappe-bench/frappe_docker/frappe/frappe-bench/apps/frappe
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            yarn install